env = "release"

[server]
addr = "0.0.0.0:19000"

[Trace]
    ServiceName = "gateway"
    Gen128Bit = true
[Trace.Sampler]
    Type = "const"
    Param = 1.0
[Trace.Reporter]
    LogSpans = true
    LocalAgentHostPort = "txchat-jaeger:6831"

[AnswerRPCClient]
    RegAddrs = "txchat-etcd:2379"
    Schema = "dtalk"
    SrvName = "answer"
    Dial = "1s"
    Timeout = "1s"

[StoreRPCClient]
    RegAddrs = "txchat-etcd:2379"
    Schema = "dtalk"
    SrvName = "store"
    Dial = "1s"
    Timeout = "1s"

[GroupRPCClient]
    RegAddrs = "txchat-etcd:2379"
    Schema = "dtalk"
    SrvName = "group"
    Dial = "1s"
    Timeout = "1s"

[[modules]]
    Name = "wallet"
    IsEnabled = true
    EndPoints = ["http://172.16.101.87:8901","http://172.16.101.107:8083"]   # changeme (1. 红包服务 http 服务地址, 2. 钱包服务 http 服务地址)

[[modules]]
    Name = "redPacket"
    IsEnabled = true
    EndPoints = ["http://172.16.101.87:8901","http://172.16.101.107:8083"]   # changeme (1. 红包服务 http 服务地址, 2. 钱包服务 http 服务地址)

[[modules]]
    Name = "oa"
    IsEnabled = true
    EndPoints = ["http://127.0.0.1:20000"]        # changeme (oa 服务地址)

[[modules]]
    Name = "shop"
    IsEnabled = true
    EndPoints = ["http://146.56.218.121:12009"]     # changeme (链上购服务地址)

[[modules]]
    Name="live"
    IsEnabled=true
    EndPoints=[""]

[Revoke]
    Expire = "86400h" #ten years (撤回消息有效时间)