AppId=     "dtalk"
Engine=    "standard"
Env= "release"

[log]
    Level="info"
    Mode="console"
    Path=""
    Display="json"

[Trace]
    ServiceName = "pusher"
    Gen128Bit = true
[Trace.Sampler]
    Type="const"
    Param=1.0
[Trace.Reporter]
    LogSpans = true
    LocalAgentHostPort = "txchat-jaeger:6831"

[GRPCServer]
    Network=                           "tcp"
    Addr=                              ":30003"
    Timeout=                           "1s"
    KeepAliveMaxConnectionIdle=        "60s"
    KeepAliveMaxConnectionAge=         "2h"
    KeepAliveMaxMaxConnectionAgeGrace= "20s"
    KeepAliveTime=                     "60s"
    KeepAliveTimeout=                  "20s"

[reg]
    schema = "dtalk"
    srvName = "pusher"
    regAddrs = "txchat-etcd:2379"

[LogicRPCClient]
    regAddrs = "txchat-etcd:2379"
    Schema = "im"
    SrvName = "logic"
    Dial = "1s"
    Timeout = "1s"

[idGenRPCClient]
    regAddrs = "txchat-etcd:2379"
    schema = "dtalk"
    srvName = "generator"
    dial = "1s"
    timeout = "1s"

[GroupRPCClient]
    regAddrs = "txchat-etcd:2379"
    schema = "dtalk"
    srvName = "group"
    dial = "1s"
    timeout = "1s"

[AnswerRPCClient]
    regAddrs = "txchat-etcd:2379"
    schema = "dtalk"
    srvName = "answer"
    dial = "1s"
    timeout = "1s"

[DeviceRPCClient]
    regAddrs = "txchat-etcd:2379"
    schema = "dtalk"
    srvName = "device"
    dial = "1s"
    timeout = "1s"

[Redis]
    network="tcp"
    addr="txchat-redis:6379"
    auth=""
    active=60000
    idle=1024
    dialTimeout="200ms"
    readTimeout="500ms"
    writeTimeout="500ms"
    idleTimeout="120s"
    expire="30m"

[IMSub]
    Brokers=["txchat-kafka:9092"]
    Number=16
    MaxWorker=1024

[RevSub]
    Brokers=["txchat-kafka:9092"]
    Number=16
    MaxWorker=1024

[StorePub]
    Brokers = ["txchat-kafka:9092"]

[OffPush]
    IsEnabled = true

[OffPush.OffPushPub]
    Brokers = ["txchat-kafka:9092"]
