AppId = "dtalk"
Engine = "standard"
Env = "debug"

[log]
Level="debug"
Mode="console"
Path=""
Display="json"

[Trace]
    ServiceName = "answer"
Gen128Bit = true
[Trace.Sampler]
    Type="const"
    Param=1.0
[Trace.Reporter]
LogSpans = true
LocalAgentHostPort = "127.0.0.1:6831"

[GRPCServer]
Network=                           "tcp"
Addr=                              ":30004"
Timeout=                           "1s"
KeepAliveMaxConnectionIdle=        "60s"
KeepAliveMaxConnectionAge=         "2h"
KeepAliveMaxMaxConnectionAgeGrace= "20s"
KeepAliveTime=                     "60s"
KeepAliveTimeout=                  "20s"

[reg]
schema = "dtalk"
srvName = "answer"
regAddrs = "127.0.0.1:2379"

[LogicRPCClient]
regAddrs = "127.0.0.1:2379"
Schema = "im"
SrvName = "logic"
Dial = "1s"
Timeout = "1s"

[idGenRPCClient]
regAddrs = "127.0.0.1:2379"
schema = "dtalk"
srvName = "generator"
dial = "1s"
timeout = "1s"

[GroupRPCClient]
regAddrs = "127.0.0.1:2379"
schema = "dtalk"
srvName = "group"
dial = "1s"
timeout = "1s"

[Redis]
network = "tcp"
addr = "127.0.0.1:6379"
auth = ""
active = 60000
idle = 1024
dialTimeout = "200ms"
readTimeout = "500ms"
writeTimeout = "500ms"
idleTimeout = "120s"
expire = "30m"

[MQSub]
Brokers = ["127.0.0.1:9092"]
Number = 16
MaxWorker = 1024

[MQPub]
Brokers = ["127.0.0.1:9092"]