definitions:
  model.GeneralResponse:
    properties:
      data: {}
      message:
        type: integer
      result:
        type: integer
    type: object
  model.GetPriRecordsReq:
    properties:
      count:
        description: 消息数量
        maximum: 100
        minimum: 1
        type: integer
      logId:
        description: 消息 ID
        type: string
      targetId:
        description: 接受者 ID
        type: string
    required:
    - count
    - targetId
    type: object
  model.GetPriRecordsResp:
    properties:
      record_count:
        description: 聊天记录数量
        type: integer
      records:
        description: 聊天记录
        items:
          $ref: '#/definitions/model.Record'
        type: array
    type: object
  model.Record:
    properties:
      content:
        description: 消息内容
      createTime:
        description: 消息发送时间
        type: integer
      fromId:
        description: 发送者 id
        type: string
      logId:
        description: log id
        type: string
      msgId:
        description: msg id (uuid)
        type: string
      msgType:
        description: 消息类型
        type: integer
      targetId:
        description: 接收者 id
        type: string
    type: object
host: 127.0.0.1:18015
info:
  contact: {}
  title: 聊天记录
  version: "1.0"
paths:
  /app/pri-chat-record:
    post:
      parameters:
      - description: MOCK
        in: header
        name: FZM-SIGNATURE
        required: true
        type: string
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/model.GetPriRecordsReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.GetPriRecordsResp'
              type: object
      summary: 获得聊天记录
      tags:
      - record 获得聊天记录
swagger: "2.0"
