// Code generated by goctl. DO NOT EDIT!
// Source: offline.proto

package server

import (
	"github.com/txchat/dtalk/app/services/offline/internal/svc"
	"github.com/txchat/dtalk/app/services/offline/offline"
)

type OfflineServer struct {
	svcCtx *svc.ServiceContext
	offline.UnimplementedOfflineServer
}

func NewOfflineServer(svcCtx *svc.ServiceContext) *OfflineServer {
	return &OfflineServer{
		svcCtx: svcCtx,
	}
}
