version: "2.4"
services:
  center:
    image: txchat-center:${CENTER_IMAGE}
    container_name: ${CENTER_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${CENTER_CONFIG_VOLUME}:/etc/txchat-center/config
  chat:
    image: txchat-chat:${CHAT_IMAGE}
    container_name: ${CHAT_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${CHAT_CONFIG_VOLUME}:/etc/txchat-chat/config
  backup:
    image: txchat-backup:${BACKUP_IMAGE}
    container_name: ${BACKUP_CONTAINER_NAME}
    environment:
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: txchat-mysql
      ETCD_HOST: txchat-etcd
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${BACKUP_CONFIG_VOLUME}:/etc/txchat-backup/config
    depends_on:
      mysql:
        condition: service_healthy
  call:
    image: txchat-call:${CALL_IMAGE}
    container_name: ${CALL_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
      REDIS_HOST: txchat-redis
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${CALL_CONFIG_VOLUME}:/etc/txchat-call/config
  device:
    image: txchat-device:${DEVICE_IMAGE}
    container_name: ${DEVICE_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
      REDIS_HOST: txchat-redis
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${DEVICE_CONFIG_VOLUME}:/etc/txchat-device/config
  generator:
    image: txchat-generator:${GENERATOR_IMAGE}
    container_name: ${GENERATOR_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${GENERATOR_CONFIG_VOLUME}:/etc/txchat-generator/config
  group:
    image: txchat-group:${GROUP_IMAGE}
    container_name: ${GROUP_CONTAINER_NAME}
    environment:
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: txchat-mysql
      ETCD_HOST: txchat-etcd
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${GROUP_CONFIG_VOLUME}:/etc/txchat-group/config
    depends_on:
      mysql:
        condition: service_healthy
  offline:
    image: txchat-offline:${OFFLINE_IMAGE}
    container_name: ${OFFLINE_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
      KAFKA_HOST: txchat-kafka
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${OFFLINE_CONFIG_VOLUME}:/etc/txchat-offline/config
  oss:
    image: txchat-oss:${OSS_IMAGE}
    container_name: ${OSS_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
      REDIS_HOST: txchat-redis
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${OSS_CONFIG_VOLUME}:/etc/txchat-oss/config
  version:
    image: txchat-version:${VERSION_IMAGE}
    container_name: ${VERSION_CONTAINER_NAME}
    environment:
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: txchat-mysql
      ETCD_HOST: txchat-etcd
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${VERSION_CONFIG_VOLUME}:/etc/txchat-version/config
    depends_on:
      mysql:
        condition: service_healthy
  transfer:
    image: txchat-transfer:${TRANSFER_IMAGE}
    container_name: ${TRANSFER_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
      KAFKA_HOST: txchat-kafka
      REDIS_HOST: txchat-redis
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${TRANSFER_CONFIG_VOLUME}:/etc/txchat-transfer/config
  pusher:
    image: txchat-pusher:${PUSHER_IMAGE}
    container_name: ${PUSHER_CONTAINER_NAME}
    environment:
      ETCD_HOST: txchat-etcd
      KAFKA_HOST: txchat-kafka
      REDIS_HOST: txchat-redis
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${PUSHER_CONFIG_VOLUME}:/etc/txchat-pusher/config
    depends_on:
      transfer:
        condition: service_started
  storage:
    image: txchat-storage:${STORAGE_IMAGE}
    container_name: ${STORAGE_CONTAINER_NAME}
    environment:
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_HOST: txchat-mysql
      ETCD_HOST: txchat-etcd
      KAFKA_HOST: txchat-kafka
      REDIS_HOST: txchat-redis
    networks:
      - txchat-components
      - txchat-service
    volumes:
      - ${STORAGE_CONFIG_VOLUME}:/etc/txchat-storage/config
    depends_on:
      mysql:
        condition: service_healthy
      device:
        condition: service_started
      pusher:
        condition: service_started
      group:
        condition: service_started
networks:
  txchat-components:
    external: true
  txchat-service:
    external: true
volumes:
  txchat-center-config:
    external: true
  txchat-chat-config:
    external: true
  txchat-backup-config:
    external: true
  txchat-call-config:
    external: true
  txchat-device-config:
    external: true
  txchat-generator-config:
    external: true
  txchat-group-config:
    external: true
  txchat-offline-config:
    external: true
  txchat-oss-config:
    external: true
  txchat-version-config:
    external: true
  txchat-transfer-config:
    external: true
  txchat-pusher-config:
    external: true
  txchat-storage-config:
    external: true