Env = "debug"

[server]
addr = "0.0.0.0:18103"

[MySQL]
Host = "127.0.0.1"
Port = 3306
User = "root"
Pwd = "root"
Db = "dtalk"

[Reg]
Schema = "dtalk"
SrvName = "auth"
RegAddrs = "127.0.0.1:2379"

[GRPCServer]
Network = "tcp"
Addr = ":18104"
Timeout = "1s"
KeepAliveMaxConnectionIdle = "60s"
KeepAliveMaxConnectionAge = "2h"
KeepAliveMaxMaxConnectionAgeGrace = "20s"
KeepAliveTime = "60s"
KeepAliveTimeout = "20s"

[Key]
KeyExpireDuration = 60000000000