#基础配置
basic_config:
  #请求方式（POST/GET）
  method: POST

  #请求目标url
  url: http://127.0.0.1:18002/user/login

#请求内容
request:
  #token字段的名称（token位于header中)
  token_name: FZM-SIGNATURE

#响应内容(响应的body内容应为json格式)
response:
  #uid的字段名
  uid_name: address

  #判断鉴权通过的关键字段的内容（字段内容要唯一）
  success_result:
    result: 0