// Code generated by goctl. DO NOT EDIT!
// Source: backup.proto

package server

import (
	"context"

	"github.com/txchat/dtalk/app/services/backup/backup"
	"github.com/txchat/dtalk/app/services/backup/internal/logic"
	"github.com/txchat/dtalk/app/services/backup/internal/svc"
)

type BackupServer struct {
	svcCtx *svc.ServiceContext
	backup.UnimplementedBackupServer
}

func NewBackupServer(svcCtx *svc.ServiceContext) *BackupServer {
	return &BackupServer{
		svcCtx: svcCtx,
	}
}

func (s *BackupServer) QueryBind(ctx context.Context, in *backup.QueryBindReq) (*backup.QueryBindResp, error) {
	l := logic.NewQueryBindLogic(ctx, s.svcCtx)
	return l.QueryBind(in)
}

func (s *BackupServer) QueryRelated(ctx context.Context, in *backup.QueryRelatedReq) (*backup.QueryRelatedResp, error) {
	l := logic.NewQueryRelatedLogic(ctx, s.svcCtx)
	return l.QueryRelated(in)
}

func (s *BackupServer) UpdateAddressBackup(ctx context.Context, in *backup.UpdateAddressBackupReq) (*backup.UpdateAddressBackupResp, error) {
	l := logic.NewUpdateAddressBackupLogic(ctx, s.svcCtx)
	return l.UpdateAddressBackup(in)
}

func (s *BackupServer) UpdateAddressRelated(ctx context.Context, in *backup.UpdateAddressRelatedReq) (*backup.UpdateAddressRelatedResp, error) {
	l := logic.NewUpdateAddressRelatedLogic(ctx, s.svcCtx)
	return l.UpdateAddressRelated(in)
}

func (s *BackupServer) UpdateMnemonic(ctx context.Context, in *backup.UpdateMnemonicReq) (*backup.UpdateMnemonicResp, error) {
	l := logic.NewUpdateMnemonicLogic(ctx, s.svcCtx)
	return l.UpdateMnemonic(in)
}
