[server]
addr="0.0.0.0:18001"

[redis]
network="tcp"
addr="127.0.0.1:6379"
auth=""
active=60000
idle=1024
dialTimeout="200ms"
readTimeout="500ms"
writeTimeout="500ms"
idleTimeout="120s"
expire="30m"

[[CNodes]]
name=""
address=""

[[DNodes]]
name=""
address=""