// Code generated by goctl. DO NOT EDIT!
// Source: generator.proto

package server

import (
	"context"

	"github.com/txchat/dtalk/app/services/generator/generator"
	"github.com/txchat/dtalk/app/services/generator/internal/logic"
	"github.com/txchat/dtalk/app/services/generator/internal/svc"
)

type GeneratorServer struct {
	svcCtx *svc.ServiceContext
	generator.UnimplementedGeneratorServer
}

func NewGeneratorServer(svcCtx *svc.ServiceContext) *GeneratorServer {
	return &GeneratorServer{
		svcCtx: svcCtx,
	}
}

func (s *GeneratorServer) GetID(ctx context.Context, in *generator.GetIDReq) (*generator.GetIDReply, error) {
	l := logic.NewGetIDLogic(ctx, s.svcCtx)
	return l.GetID(in)
}
