// Code generated by goctl. DO NOT EDIT!
// Source: pusher.proto

package pusherclient

import (
	"context"

	"github.com/txchat/dtalk/app/services/pusher/pusher"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	PushReply = pusher.PushReply
	PushReq   = pusher.PushReq

	Pusher interface {
		PushClient(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushReply, error)
	}

	defaultPusher struct {
		cli zrpc.Client
	}
)

func NewPusher(cli zrpc.Client) Pusher {
	return &defaultPusher{
		cli: cli,
	}
}

func (m *defaultPusher) PushClient(ctx context.Context, in *PushReq, opts ...grpc.CallOption) (*PushReply, error) {
	client := pusher.NewPusherClient(m.cli.Conn())
	return client.PushClient(ctx, in, opts...)
}
