definitions:
  model.CheckCallRequest:
    properties:
      traceId:
        type: integer
      traceIdStr:
        description: 如果同时填了 tracedIdStr, 则优先选择 traceIdStr
        type: string
    type: object
  model.CheckCallResponse:
    properties:
      RTCType:
        type: integer
      caller:
        type: string
      createTime:
        type: integer
      deadline:
        type: integer
      groupId:
        type: string
      invitees:
        items:
          type: string
        type: array
      timeout:
        type: integer
      traceId:
        type: integer
      traceIdStr:
        type: string
    type: object
  model.GeneralResponse:
    properties:
      data:
        type: object
      message:
        type: integer
      result:
        type: integer
    type: object
  model.HandleCallRequest:
    properties:
      answer:
        type: boolean
      traceId:
        type: integer
      traceIdStr:
        description: 如果同时填了 tracedIdStr, 则优先选择 traceIdStr
        type: string
    type: object
  model.HandleCallResponse:
    properties:
      privateMapKey:
        type: string
      roomId:
        type: integer
      sdkAppId:
        type: integer
      userSig:
        type: string
    type: object
  model.ReplyBusyRequest:
    properties:
      traceId:
        type: integer
      traceIdStr:
        description: 如果同时填了 tracedIdStr, 则优先选择 traceIdStr
        type: string
    type: object
  model.ReplyBusyResponse:
    type: object
  model.StartCallRequest:
    properties:
      RTCType:
        type: integer
      groupId:
        type: string
      invitees:
        items:
          type: string
        type: array
    required:
    - invitees
    type: object
  model.StartCallResponse:
    properties:
      RTCType:
        type: integer
      caller:
        type: string
      createTime:
        type: integer
      deadline:
        type: integer
      groupId:
        description: 0表示私聊, 其他表示群聊
        type: string
      invitees:
        items:
          type: string
        type: array
      timeout:
        type: integer
      traceId:
        type: integer
      traceIdStr:
        type: string
    type: object
host: 127.0.0.1:18013
info:
  contact: {}
  title: 音视频信令服务接口
  version: "1.0"
paths:
  /app/check-call:
    post:
      parameters:
      - description: MOCK
        in: header
        name: FZM-SIGNATURE
        required: true
        type: string
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/model.CheckCallRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.CheckCallResponse'
              type: object
      summary: 检查通话状态
      tags:
      - call
  /app/handle-call:
    post:
      parameters:
      - description: MOCK
        in: header
        name: FZM-SIGNATURE
        required: true
        type: string
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/model.HandleCallRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.HandleCallResponse'
              type: object
      summary: 处理通话
      tags:
      - call
  /app/reply-busy:
    post:
      parameters:
      - description: MOCK
        in: header
        name: FZM-SIGNATURE
        required: true
        type: string
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/model.ReplyBusyRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.ReplyBusyResponse'
              type: object
      summary: 返回忙碌
      tags:
      - call
  /app/start-call:
    post:
      parameters:
      - description: MOCK
        in: header
        name: FZM-SIGNATURE
        required: true
        type: string
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/model.StartCallRequest'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/model.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/model.StartCallResponse'
              type: object
      summary: 开始通话
      tags:
      - call
swagger: "2.0"
