Node=1

[reg]
    Schema = "dtalk"
    SrvName = "generator"
    RegAddrs = "txchat-etcd:2379"

[GRPCServer]
    Network=                           "tcp"
    Addr=                              ":30002"
    Timeout=                           "1s"
    KeepAliveMaxConnectionIdle=        "60s"
    KeepAliveMaxConnectionAge=         "2h"
    KeepAliveMaxMaxConnectionAgeGrace= "20s"
    KeepAliveTime=                     "60s"
    KeepAliveTimeout=                  "20s"