AppId = "dtalk"
Engine = "standard"
Env = "debug"
SyncCache = false

[log]
Level = "debug"
Mode = "console"
Path = ""
Display = "json"

[Trace]
ServiceName = "store"
Gen128Bit = true
[Trace.Sampler]
Type = "const"
Param = 1.0
[Trace.Reporter]
LogSpans = true
LocalAgentHostPort = "127.0.0.1:6831"

[GRPCrver]
Network=                           "tcp"
Addr=                              ":30005"
Timeout=                           "1s"
KeepAliveMaxConnectionIdle=        "60s"
KeepAliveMaxConnectionAge=         "2h"
KeepAliveMaxMaxConnectionAgeGrace= "20s"
KeepAliveTime=                     "60s"
KeepAliveTimeout=                  "20s"


[reg]
    schema = "dtalk"
    srvName = "store"
    regAddrs = "127.0.0.1:2379"

[GroupRPCClient]
    regAddrs = "127.0.0.1:2379"
    schema = "dtalk"
    srvName = "group"
    dial = "1s"
    timeout = "1s"

[MySQL]
Host= "127.0.0.1"
Port= 3306
User= "root"
Pwd=  "123456"
Db=   "dtalk"

[Redis]
network="tcp"
addr="127.0.0.1:6379"
auth=""
active=60000
idle=1024
dialTimeout="200ms"
readTimeout="500ms"
writeTimeout="500ms"
idleTimeout="120s"
expire="30m"

[PusherRPCClient]
    regAddrs = "127.0.0.1:2379"
    schema = "dtalk"
    srvName = "pusher"
    dial = "1s"
    timeout = "1s"

[RevSub]
Brokers=["127.0.0.1:9092"]
Number=16
MaxWorker=1024

[StoreSub]
Brokers=["127.0.0.1:9092"]
Number=16
MaxWorker=1024