AppId = "dtalk"
Engine = "standard"
Env = "release"
SyncCache = false

[log]
Level = "info"
Mode = "console"
Path = ""
Display = "json"

[Trace]
    ServiceName = "store"
    Gen128Bit = true
[Trace.Sampler]
    Type = "const"
    Param = 1.0
[Trace.Reporter]
    LogSpans = true
    LocalAgentHostPort = "txchat-jaeger:6831"

[GRPCrver]
    Network=                           "tcp"
    Addr=                              ":30005"
    Timeout=                           "1s"
    KeepAliveMaxConnectionIdle=        "60s"
    KeepAliveMaxConnectionAge=         "2h"
    KeepAliveMaxMaxConnectionAgeGrace= "20s"
    KeepAliveTime=                     "60s"
    KeepAliveTimeout=                  "20s"

[MySQL]
    Host= "txchat-mysql"
    Port= 3306
    User= "root"
    Pwd=  "123456"
    Db=   "dtalk_record"

[Redis]
    network="tcp"
    addr="txchat-redis:6379"
    auth=""
    active=60000
    idle=1024
    dialTimeout="200ms"
    readTimeout="500ms"
    writeTimeout="500ms"
    idleTimeout="120s"
    expire="30m"

[reg]
    schema = "dtalk"
    srvName = "store"
    regAddrs = "txchat-etcd:2379"

[GroupRPCClient]
    regAddrs = "txchat-etcd:2379"
    schema = "dtalk"
    srvName = "group"
    dial = "1s"
    timeout = "1s"

[DeviceRPCClient]
    regAddrs = "txchat-etcd:2379"
    schema = "dtalk"
    srvName = "device"
    dial = "1s"
    timeout = "1s"

[PusherRPCClient]
    regAddrs = "txchat-etcd:2379"
    schema = "dtalk"
    srvName = "pusher"
    dial = "1s"
    timeout = "1s"

[RevSub]
    Brokers=["txchat-kafka:9092"]
    Number=16
    MaxWorker=1024

[StoreSub]
    Brokers=["txchat-kafka:9092"]
    Number=16
    MaxWorker=1024