Env   = "release"
AppId = "dtalk"
Node  = 1

[HttpServer]
    Addr = "0.0.0.0:18013"

[Redis]
    network      = "tcp"
    addr         = "txchat-redis:6379"
    auth         = ""
    active       = 60000
    idle         = 1024
    dialTimeout  = "200ms"
    readTimeout  = "500ms"
    writeTimeout = "500ms"
    idleTimeout  = "120s"
    expire       = "30m"

[IdGenRPCClient]
    RegAddrs = "txchat-etcd:2379"
    Schema  = "dtalk"
    SrvName = "generator"
    Dial    = "1s"
    Timeout = "1s"

[AnswerRPCClient]
    RegAddrs = "txchat-etcd:2379"
    Schema  = "dtalk"
    SrvName = "answer"
    Dial    = "1s"
    Timeout = "1s"

[TCRTCConfig]
    SDKAppId  = 1400543084
    SecretKey = "1ed1b5e2729395c1e8b55b83be72e60139dfa36ff3fa67bc3c3285592a7b3cf6"
    Expire    = 86400

