env="release"

[log]
    Level="info"
    Mode="console"
    Path=""
    Display="json"

[GroupRPCClient]
    RegAddrs = "txchat-etcd:2379"
    Schema = "dtalk"
    SrvName = "group"
    Dial = "1s"
    Timeout = "1s"

[SlgHTTPClient]
    Host = "http://localhost:8888"
    Salt = ""

#Field name   | Mandatory? | Allowed values  | Allowed special characters
#----------   | ---------- | --------------  | --------------------------
#Seconds      | Yes        | 0-59            | * / , -
#Minutes      | Yes        | 0-59            | * / , -
#Hours        | Yes        | 0-23            | * / , -
#Day of month | Yes        | 1-31            | * / , - ?
#Month        | Yes        | 1-12 or JAN-DEC | * / , -
#Day of week  | Yes        | 0-6 or SUN-SAT  | * / , - ?
# https://pkg.go.dev/github.com/robfig/cron#Cron.AddFunc
TaskSpec = "00 00 00 * * *"