definitions:
  types.Cdk:
    properties:
      cdkContent:
        type: string
      cdkId:
        type: string
      cdkName:
        type: string
      cdkStatus:
        type: integer
      createTime:
        type: string
      exchangeTime:
        type: string
      id:
        type: string
      orderId:
        type: string
      userId:
        type: string
    type: object
  types.CdkType:
    properties:
      cdkAvailable:
        description: 未发放的cdk数量
        type: integer
      cdkFrozen:
        description: 冻结状态中的cdk数量
        type: integer
      cdkId:
        type: string
      cdkInfo:
        type: string
      cdkName:
        type: string
      cdkUsed:
        description: 已发放的cdk数量
        type: integer
      coinName:
        type: string
      exchangeRate:
        type: integer
    type: object
  types.CreateCdkOrderReq:
    properties:
      cdkId:
        description: cdk 种类编号
        type: string
      number:
        description: 兑换数量
        type: integer
    required:
    - cdkId
    - number
    type: object
  types.CreateCdkOrderResp:
    properties:
      orderId:
        description: 订单编号
        type: string
    type: object
  types.CreateCdkTypeReq:
    properties:
      cdkInfo:
        type: string
      cdkName:
        type: string
      coinName:
        type: string
      exchangeRate:
        type: integer
    required:
    - coinName
    - exchangeRate
    type: object
  types.CreateCdkTypeResp:
    properties:
      cdkId:
        type: string
    type: object
  types.CreateCdksReq:
    properties:
      cdkContents:
        items:
          type: string
        type: array
      cdkId:
        type: string
    required:
    - cdkContents
    - cdkId
    type: object
  types.CreateCdksResp:
    type: object
  types.DealCdkOrderReq:
    properties:
      orderId:
        description: 订单编号
        type: string
      result:
        description: 处理结果
        type: boolean
      transferHash:
        description: 转账记录 hash
        type: string
    required:
    - orderId
    - transferHash
    type: object
  types.DealCdkOrderResp:
    type: object
  types.DeleteCdkTypesReq:
    properties:
      cdkIds:
        items:
          type: string
        type: array
    required:
    - cdkIds
    type: object
  types.DeleteCdkTypesResp:
    type: object
  types.DeleteCdksReq:
    properties:
      ids:
        items:
          type: string
        type: array
    required:
    - ids
    type: object
  types.DeleteCdksResp:
    type: object
  types.ExchangeCdksReq:
    properties:
      ids:
        items:
          type: string
        type: array
    required:
    - ids
    type: object
  types.ExchangeCdksResp:
    type: object
  types.GeneralResponse:
    properties:
      data: {}
      message:
        type: integer
      result:
        type: integer
    type: object
  types.GetCdkTypeByCoinNameReq:
    properties:
      coinName:
        type: string
    required:
    - coinName
    type: object
  types.GetCdkTypeByCoinNameResp:
    properties:
      cdkAvailable:
        description: 未发放的cdk数量
        type: integer
      cdkFrozen:
        description: 冻结状态中的cdk数量
        type: integer
      cdkId:
        type: string
      cdkInfo:
        type: string
      cdkName:
        type: string
      cdkUsed:
        description: 已发放的cdk数量
        type: integer
      coinName:
        type: string
      exchangeRate:
        type: integer
    type: object
  types.GetCdkTypesReq:
    properties:
      coinName:
        type: string
      page:
        description: 页数
        type: integer
      pageSize:
        description: 每页数量
        type: integer
    type: object
  types.GetCdkTypesResp:
    properties:
      cdkTypes:
        items:
          $ref: '#/definitions/types.CdkType'
        type: array
      totalElements:
        type: integer
      totalPages:
        type: integer
    type: object
  types.GetCdksByUserIdReq:
    properties:
      page:
        description: 页数
        type: integer
      pageSize:
        description: 每页数量
        type: integer
    type: object
  types.GetCdksByUserIdResp:
    properties:
      cdks:
        items:
          $ref: '#/definitions/types.Cdk'
        type: array
      totalElements:
        type: integer
      totalPages:
        type: integer
    type: object
  types.GetCdksReq:
    properties:
      cdkContent:
        type: string
      cdkId:
        type: string
      page:
        description: 页数
        type: integer
      pageSize:
        description: 每页数量
        type: integer
    required:
    - cdkId
    type: object
  types.GetCdksResp:
    properties:
      cdks:
        items:
          $ref: '#/definitions/types.Cdk'
        type: array
      totalElements:
        type: integer
      totalPages:
        type: integer
    type: object
  types.UpdateCdkTypeReq:
    properties:
      cdkId:
        type: string
      cdkName:
        type: string
      coinName:
        type: string
      exchangeRate:
        type: integer
    required:
    - cdkId
    - cdkName
    - coinName
    - exchangeRate
    type: object
  types.UpdateCdkTypeResp:
    type: object
info:
  contact: {}
paths:
  /app/cdk/create-cdk-order:
    post:
      parameters:
      - description: MOCK
        in: header
        name: FZM-SIGNATURE
        required: true
        type: string
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.CreateCdkOrderReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.CreateCdkOrderResp'
              type: object
      summary: 创建兑换订单
      tags:
      - Cdk App
  /app/cdk/deal-cdk-order:
    post:
      parameters:
      - description: MOCK
        in: header
        name: FZM-SIGNATURE
        required: true
        type: string
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.DealCdkOrderReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.DealCdkOrderResp'
              type: object
      summary: 处理兑换订单
      tags:
      - Cdk App
  /app/cdk/get-cdk-type-by-coin-name:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.GetCdkTypeByCoinNameReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.GetCdkTypeByCoinNameResp'
              type: object
      summary: 查询一个票券对应的 cdkType
      tags:
      - Cdk App
  /app/cdk/get-cdks-by-user-id:
    post:
      parameters:
      - description: MOCK
        in: header
        name: FZM-SIGNATURE
        required: true
        type: string
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.GetCdksByUserIdReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.GetCdksByUserIdResp'
              type: object
      summary: 分页获得一个人拥有的 cdks
      tags:
      - Cdk App
  /backend/cdk/create-cdk-type:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.CreateCdkTypeReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.CreateCdkTypeResp'
              type: object
      summary: 创建 CdkType
      tags:
      - Cdk 后台
  /backend/cdk/create-cdks:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.CreateCdksReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.CreateCdksResp'
              type: object
      summary: 创建 Cdks
      tags:
      - Cdk 后台
  /backend/cdk/delete-cdk-types:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.DeleteCdkTypesReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.DeleteCdkTypesResp'
              type: object
      summary: 删除 cdkTypes
      tags:
      - Cdk 后台
  /backend/cdk/delete-cdks:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.DeleteCdksReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.DeleteCdksResp'
              type: object
      summary: 删除 cdks
      tags:
      - Cdk 后台
  /backend/cdk/exchange-cdks:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.ExchangeCdksReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.ExchangeCdksResp'
              type: object
      summary: 兑换 cdks
      tags:
      - Cdk 后台
  /backend/cdk/get-cdk-types:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.GetCdkTypesReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.GetCdkTypesResp'
              type: object
      summary: 分页获得 cdkType
      tags:
      - Cdk 查询
  /backend/cdk/get-cdks:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.GetCdksReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.GetCdksResp'
              type: object
      summary: 分页获得 cdks
      tags:
      - Cdk 查询
  /backend/cdk/update-cdk-type:
    post:
      parameters:
      - description: body
        in: body
        name: data
        schema:
          $ref: '#/definitions/types.UpdateCdkTypeReq'
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/types.GeneralResponse'
            - properties:
                data:
                  $ref: '#/definitions/types.UpdateCdkTypeResp'
              type: object
      summary: 更新 cdkType
      tags:
      - Cdk 后台
swagger: "2.0"
