name: static-analysis
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
  workflow_dispatch:

jobs:
  gofmtcheck:
    name: gofmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: run check format shell
        run: |
          make checkgofmt
        shell: bash
  # https://github.com/marketplace/actions/run-golangci-lint
  golangci:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: v1.46
          # Optional: show only new issues if it's a pull request. The default value is `false`.
          only-new-issues: true
  # https://github.com/marketplace/actions/shellcheck
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: ShellCheck
        uses: ludeeus/action-shellcheck@1.1.0
