// Code generated by goctl. DO NOT EDIT!
// Source: offline.proto

package offlineclient

import (
	"github.com/zeromicro/go-zero/zrpc"
)

type (
	Offline interface {
	}

	defaultOffline struct {
		cli zrpc.Client
	}
)

func NewOffline(cli zrpc.Client) Offline {
	return &defaultOffline{
		cli: cli,
	}
}
