// Code generated by goctl. DO NOT EDIT!
// Source: offline.proto

package offlineclient

import (
	"context"

	"github.com/txchat/dtalk/app/services/offline/offline"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = offline.Request
	Response = offline.Response

	Offline interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultOffline struct {
		cli zrpc.Client
	}
)

func NewOffline(cli zrpc.Client) Offline {
	return &defaultOffline{
		cli: cli,
	}
}

func (m *defaultOffline) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := offline.NewOfflineClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
